# -*- coding: utf-8 -*-
"""Titanic_survival.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1b59IiNLR1F6bAnCM7BRxwN7sIrUfDV
"""

import pandas as pd

data = pd.read_csv('titanic.csv')

df = pd.DataFrame(data)

df.head()

df.info()

modified_age = df['Age'].mean()

df['Age'] = df['Age'].fillna(modified_age)

df['Sex'] = df['Sex'].replace({'male':0, 'female':1})

df.info()

df.head(10)

df[['Survived', 'Age']].isna().sum()

corr = df[['Survived', 'Age', 'Sex', 'Pclass']].corr()

display(corr)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize = (10, 10))
sns.heatmap(corr, annot = True, cmap = 'coolwarm')

df[['Age', 'Sex', 'Pclass', 'Survived']].hist(figsize=(10, 10), bins = 10)
plt.show()

x = df[['Age', 'Sex', 'Pclass']]
y = df[ 'Survived']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

model = LogisticRegression()
model.fit(x_train, y_train)

try:
    age = int(input("Enter age: "))
    sex = int(input("Enter sex (Male-0, Female - 1): "))
    pclass = int(input("Enter pclass (1, 2, 3): "))

    if sex not in [0, 1] or pclass not in [1, 2, 3]:
        raise ValueError("Invalid input for sex or pclass.")

    input_df = pd.DataFrame([[age, sex, pclass]], columns=['Age', 'Sex', 'Pclass'])
    res = model.predict(input_df)

    if res[0] == 1:
        print("Survived")
    else:
        print("Dead")
    print("Model accuracy on test set:", accuracy_score(y_test, y_test_pred))

except ValueError as e:
    print("Invalid input:", e)